################################################################################
# File:     .travis.yml
# Author:   GAndaLF
# Brief:    Configuration file for Travis-CI continuous integration tool.
################################################################################

sudo: false

# Cache storing toolchain compiled from source
cache:
  directories:
    - "${HOME}/cache"

# Turn off default travis email notifications
notifications:
  email: false

# install packages needed by toolchain and gcc-4.8 with gnu++11 support.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - texinfo
      - texlive

language: generic

script:
  - chmod +x scripts/install_bleeding_edge_toolchain.sh
  - ./scripts/install_bleeding_edge_toolchain.sh
  - cd ${HOME}/toolchains/arm-none-eabi-gcc-6.3.0-*/bin; export PATH=$PATH:$(pwd); echo $PATH; cd ${TRAVIS_BUILD_DIR}
  - make

after_failure:
  - tail -n 1000 /tmp/stdout.log
  - tail -n 1000 /tmp/stderr.log