################################################################################
# File:     .travis.yml
# Author:   GAndaLF
# Brief:    Configuration file for Travis-CI continuous integration tool.
################################################################################

sudo: false

# Trusty becomes default distribution due to end of support for precise
# For now trusty cannot be used for this project due to exceeding build time limit.
dist: precise

# Cache storing toolchain compiled from source
cache:
  directories:
    - "${HOME}/cache"

# Turn off default travis email notifications
notifications:
  email: false

# environmental variables
env:
  - XZ_OPT="-0 -T 0 -v"
  
# install packages needed by toolchain and gcc-4.8 with gnu++11 support.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - texinfo
      - texlive

language: generic

script:
  - chmod +x scripts/install_bleeding_edge_toolchain.sh
  - ./scripts/install_bleeding_edge_toolchain.sh
  - cd ${HOME}/toolchains/arm-none-eabi-gcc-*/bin; export PATH=$PATH:$(pwd); echo $PATH; cd ${TRAVIS_BUILD_DIR}
  - make

after_failure:
  - tail -n 1000 /tmp/stdout.log
  - tail -n 1000 /tmp/stderr.log